name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        working-directory: ./vreal0_1
      - run: |

          cd vreal0_1/build/web
          git init

          git config --global user.email artistj1015@gmail.com

          git config --global user.name sohnsmtih
          git status

          git remote add origin https://github.com/sohnsmith/vreal0.1.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f